development:
  adapter: postgresql
  database: bullhorn_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bullhorn_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: bullhorn_production
  pool: 5
  timeout: 5000
